"""add outbox table

Revision ID: 7b0773a15bfd
Revises: 8c48faca5258
Create Date: 2026-08-25 15:58:35.494513

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b0773a15bfd"
down_revision: Union[str, Sequence[str], None] = "8c48faca5258"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("outbox_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "ticket_purchased", name="outboxeventtype", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "sent", name="outboxstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("outbox_id"),
    )
    op.create_index(op.f("ix_outbox_status"), "outbox", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outbox_status"), table_name="outbox")
    op.drop_table("outbox")
    # ### end Alembic commands ###
